/* Search index — bilingual. Edit these entries when adding/removing content. */
window.SEARCH_INDEX = [
  // ----- Pre-install -----
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html',
    title: 'Qualcomm 帳號註冊', titleEn: 'Register Qualcomm account',
    body: '開始前先到 qualcomm.com 註冊，QSC 登入與 AI Hub 都會用到',
    bodyEn: 'Register at qualcomm.com first — needed for QSC sign-in and AI Hub.',
    tags: ['qualcomm', 'account', '帳號', 'register'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-adb',
    title: 'adb (platform-tools)', titleEn: 'adb (platform-tools)',
    body: '連線 / 除錯平台，Windows 解壓 platform-tools，Ubuntu apt install adb',
    bodyEn: 'Device connect / debug. Windows: platform-tools zip; Ubuntu: apt install adb.',
    tags: ['adb', 'platform-tools', '除錯', 'debug'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-qsc',
    title: 'Qualcomm Software Center (QSC)', titleEn: 'Qualcomm Software Center (QSC)',
    body: '下載 PCAT / QUD 的入口，安裝後以 Qualcomm 帳號登入',
    bodyEn: 'Gateway to download PCAT / QUD; sign in with your Qualcomm account.',
    tags: ['qsc', 'software center', 'qualcomm'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-pcat',
    title: 'PCAT Tool', titleEn: 'PCAT Tool',
    body: '燒錄 image 工具，在 QSC 的 Tools 搜尋 Product Configuration Assistant Tool',
    bodyEn: 'Image flashing tool. Search Product Configuration Assistant Tool in QSC Tools.',
    tags: ['pcat', 'flash', '燒錄', 'image'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-qud',
    title: 'QUD (Qualcomm USB Driver)', titleEn: 'QUD (Qualcomm USB Driver)',
    body: 'Qualcomm USB 驅動，從 QSC 下載安裝',
    bodyEn: 'Qualcomm USB driver, installed from QSC.',
    tags: ['qud', 'usb', 'driver', '驅動'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#ub-qdl',
    title: 'QDL（命令列燒錄工具）', titleEn: 'QDL (CLI flashing tool)',
    body: 'Ubuntu 專用，從 linux-msm/qdl 以 meson 編譯安裝',
    bodyEn: 'Ubuntu only — build from linux-msm/qdl with meson.',
    tags: ['qdl', 'meson', 'flash', 'cli'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-docker',
    title: 'Docker', titleEn: 'Docker',
    body: '容器執行環境，Windows 需 WSL2，Ubuntu 用官方腳本',
    bodyEn: 'Container runtime. Windows needs WSL2; Ubuntu uses the official script.',
    tags: ['docker', 'wsl2', 'container', '容器'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-moba',
    title: 'MobaXterm / minicom (UART)', titleEn: 'MobaXterm / minicom (UART)',
    body: 'UART 序列埠工具，看 boot log / debug。Windows 用 MobaXterm，Ubuntu 用 minicom',
    bodyEn: 'UART serial tools to read boot log / debug. MobaXterm on Windows, minicom on Ubuntu.',
    tags: ['uart', 'mobaxterm', 'minicom', 'serial', '序列埠'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-cp210x',
    title: 'CP210x USB-UART 驅動', titleEn: 'CP210x USB-UART driver',
    body: 'USB 轉序列埠，Windows 手動安裝，Ubuntu 核心內建免裝',
    bodyEn: 'USB-to-serial. Manual install on Windows; built into the Ubuntu kernel.',
    tags: ['cp210x', 'usb-uart', 'driver', 'com port'] },

  // ----- Flashing -----
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s1',
    title: 'Windows 燒錄說明書', titleEn: 'Windows flashing guide',
    body: '用 xPCATApp 將映像燒錄到 Q911 平台，先參考 README 步驟 1～3',
    bodyEn: 'Flash the image to the Q911 with xPCATApp; first follow README steps 1–3.',
    tags: ['flash', '燒錄', 'xpcatapp', 'pcat', 'q911', 'readme'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s2',
    title: 'Qualcomm Software Center / connect devices', titleEn: 'QSC / connect devices',
    body: '打開 QSC 會看到 connect devices',
    bodyEn: 'Open QSC and you will see connect devices.',
    tags: ['qsc', 'connect devices', 'qualcomm'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s4',
    title: '連線 Q911', titleEn: 'Connect to the Q911',
    body: '點擊左上角選擇要連線的 Q911',
    bodyEn: 'Click the top-left and select the Q911 to connect.',
    tags: ['q911', 'connect', 'pcat'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s6',
    title: '選 image 與 UFS memory type', titleEn: 'Choose image and UFS memory type',
    body: '選 image 資料夾、UFS 作為 memory type，確認 .elf 被正確選擇，點 download',
    bodyEn: 'Pick the image folder, UFS memory type, confirm the .elf is selected, then download.',
    tags: ['ufs', 'memory type', 'elf', 'download', 'image'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s8',
    title: '切回 Normal mode 並開機', titleEn: 'Switch back to Normal mode and boot',
    body: '燒錄完成後進行 README 步驟 5～6，切回 Normal mode 並開機',
    bodyEn: 'After flashing, do README steps 5–6: switch back to Normal mode and boot.',
    tags: ['normal mode', 'boot', '開機', 'readme'] },

  // ----- Script -----
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s0',
    title: 'Windows 主機設定（僅需一次）', titleEn: 'Windows Host Setup (one-time)',
    body: '[WIN-PS] 執行 setup-windows-wsl.ps1，準備 WSL2 Ubuntu-22.04、啟用 systemd，用 usbipd 掛載 Q911 USB',
    bodyEn: '[WIN-PS] Run setup-windows-wsl.ps1 to prepare WSL2 Ubuntu-22.04, enable systemd, attach the Q911 USB via usbipd.',
    tags: ['wsl', 'usbipd', 'powershell', 'script', '腳本', 'setup-windows-wsl'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s1',
    title: 'step_1.sh — 安裝 adb，確認 Q911 連線', titleEn: 'step_1.sh — Install adb, check Q911 connection',
    body: '[HOST] 約 1 分鐘，adb devices 應列出 EXMP-Q911',
    bodyEn: '[HOST] ~1 min. adb devices should list EXMP-Q911.',
    tags: ['adb', 'step_1', 'q911', 'connection'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s2',
    title: 'step_2.sh — 安裝 Docker，取得 iQ-Foundry image', titleEn: 'step_2.sh — Install Docker, get iQ-Foundry image',
    body: '[HOST] 安裝 Docker Engine，pull innodiskorg/iqf:latest',
    bodyEn: '[HOST] Install Docker Engine, pull innodiskorg/iqf:latest.',
    tags: ['docker', 'step_2', 'iqf'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s3',
    title: 'step_3.sh — 登入 Qualcomm AI Hub', titleEn: 'step_3.sh — Log in to Qualcomm AI Hub',
    body: '[HOST] step_3.sh <YOUR_QAI_HUB_API_KEY>，換成自己的 API token',
    bodyEn: '[HOST] step_3.sh <YOUR_QAI_HUB_API_KEY> — use your own API token.',
    tags: ['ai hub', 'qaihub', 'token', 'login', '登入', 'step_3'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s4_1',
    title: 'step_4_1.sh — FP32 匯出', titleEn: 'step_4_1.sh — FP32 export',
    body: '[HOST] 建置 iqf-aihub image，匯出 YOLO26 FP32 TFLite 模型',
    bodyEn: '[HOST] Build the iqf-aihub image, export the YOLO26 FP32 TFLite model.',
    tags: ['fp32', 'export', 'yolo26', 'tflite', 'step_4_1'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s4_2',
    title: 'step_4_2.sh — 安裝 iQ-Studio 並執行 FP32 streampipe 9ch', titleEn: 'step_4_2.sh — Install iQ-Studio and run FP32 streampipe 9ch',
    body: '[Q911 首次執行 ~3 分鐘] 推送並安裝 iQ-Studio，啟動 FP32 streampipe 9ch',
    bodyEn: '[Q911, ~3 min first run] Push and install iQ-Studio, start FP32 streampipe 9ch.',
    tags: ['iq-studio', 'streampipe', 'fp32', 'step_4_2', '9ch'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_1',
    title: 'step_5_1.sh — 部署 Q911 runtime venv', titleEn: 'step_5_1.sh — Deploy Q911 runtime venv',
    body: '[離線] 部署裝置端 venv，adb kill-server 讓出 USB 給 container',
    bodyEn: '[Offline] Deploy the device-side venv, adb kill-server to release USB for the container.',
    tags: ['venv', 'q911', 'step_5_1', 'adb kill-server'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_2',
    title: 'step_5_2.sh — iQ-Foundry 量化', titleEn: 'step_5_2.sh — iQ-Foundry quantization',
    body: '[HOST] qc 量化，把 YOLO26 .pt 量化成 INT8 .tflite',
    bodyEn: '[HOST] qc quantization — quantize YOLO26 .pt into an INT8 .tflite.',
    tags: ['quantization', '量化', 'int8', 'iqf', 'qc', 'step_5_2'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_3',
    title: 'step_5_3.sh — iQ-Foundry mAP', titleEn: 'step_5_3.sh — iQ-Foundry mAP',
    body: '[離線] 比較 FP32 與 INT8 模型的 mAP',
    bodyEn: '[Offline] Compare FP32 vs INT8 model mAP.',
    tags: ['map', 'mAP', 'iqf', 'evaluation', '評估', 'step_5_3'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_4',
    title: 'step_5_4.sh — iQ-Foundry 裝置測試', titleEn: 'step_5_4.sh — iQ-Foundry device test',
    body: '[離線] 透過 adb 在 Q911 上跑 INT8 模型推論',
    bodyEn: '[Offline] Run INT8 model inference on the Q911 via adb.',
    tags: ['device test', '裝置測試', 'adb', 'iqf', 'int8', 'step_5_4'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_5',
    title: 'step_5_5.sh — 執行 INT8 streampipe 9ch', titleEn: 'step_5_5.sh — Run INT8 streampipe 9ch',
    body: '[離線] 推送 INT8 模型/設定檔，啟動 INT8 streampipe 9ch',
    bodyEn: '[Offline] Push the INT8 model/config, start INT8 streampipe 9ch.',
    tags: ['int8', 'streampipe', 'step_5_5', '9ch'] },

  // ----- FAQ -----
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#adb',
    title: 'adb 使用方式', titleEn: 'Using adb',
    body: '從 Windows 連到平台下指令、進 shell，.\\adb.exe devices / shell',
    bodyEn: 'Connect from Windows, run commands, enter shell. .\\adb.exe devices / shell.',
    tags: ['adb', 'shell', 'devices', 'platform-tools'] },
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#adb-debug',
    title: 'adb 看不到裝置 / unauthorized', titleEn: 'adb no device / unauthorized',
    body: '確認 Flash / ADB port、平台完全開機、換線；unauthorized 或 offline 請重新插拔',
    bodyEn: 'Check the Flash / ADB port, full boot, swap cable; replug if unauthorized or offline.',
    tags: ['adb', 'unauthorized', 'offline', 'debug', '除錯'] },
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#uart',
    title: 'MobaXterm (UART) 使用方式', titleEn: 'Using MobaXterm (UART)',
    body: '最底層 debug 管道，開機卡住 / adb 連不上時看 boot log',
    bodyEn: 'Lowest-level debug channel — read the boot log when boot hangs or adb fails.',
    tags: ['uart', 'mobaxterm', 'serial', 'boot log', '序列埠'] },
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#uart-com',
    title: '找出 COM port', titleEn: 'Find the COM port',
    body: '裝置管理員 → 連接埠 (COM 和 LPT)，記下 COM 編號（例 COM5）',
    bodyEn: 'Device Manager → Ports (COM & LPT); note the COM number (e.g. COM5).',
    tags: ['com port', 'device manager', 'com5', '裝置管理員'] },
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#uart-serial',
    title: '開啟 Serial session', titleEn: 'Open a Serial session',
    body: 'MobaXterm → Session → Serial，選 COM port，Speed 115200',
    bodyEn: 'MobaXterm → Session → Serial, pick COM port, Speed 115200.',
    tags: ['serial', '115200', 'session', 'mobaxterm'] },
  { page: 'faq', pageLabel: 'FAQ', href: 'faq.html#uart-fix',
    title: 'UART 無法使用 / 驅動 / brltty', titleEn: "UART won't work / driver / brltty",
    body: 'Windows 裝 CP210x 驅動；Ubuntu 移除 brltty 後再用 minicom 連線',
    bodyEn: 'Windows: install CP210x driver. Ubuntu: remove brltty, then reconnect with minicom.',
    tags: ['cp210x', 'driver', 'brltty', 'minicom', 'dmesg', '驅動'] },

  // ----- Agenda (on homepage) -----
  { page: 'agenda', pageLabel: '議程 / AGENDA', href: 'index.html#agenda',
    title: '議程 Agenda', titleEn: 'Agenda',
    body: '2026.07.30（四）10:00–16:00，新北市汐止區大同路一段 237 號 16 樓',
    bodyEn: 'Thu 2026.07.30, 10:00–16:00 — 16F, No.237, Sec.1, Datong Rd, Xizhi, New Taipei.',
    tags: ['agenda', '議程', 'schedule', '時間', '地點', '報到', '開場', '結尾'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 10:10', href: 'index.html#agenda',
    title: '高通技術公司 — 呂承翰', titleEn: 'Qualcomm — 呂承翰',
    body: '10:10–10:40 呂承翰，Director, Business Development, Qualcomm',
    bodyEn: '10:10–10:40 呂承翰, Director, Business Development, Qualcomm.',
    tags: ['qualcomm', '高通', '呂承翰', 'business development'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 10:40', href: 'index.html#agenda',
    title: '高通邊緣平台如何重塑智慧生態系 — 吳志清', titleEn: 'Reshaping the smart ecosystem — 吳志清',
    body: '10:40–11:05 宜鼎國際 Innodisk，吳志清 智能周邊應用事業處處長',
    bodyEn: '10:40–11:05 Innodisk, 吳志清, Head of Smart Peripheral Application.',
    tags: ['innodisk', '宜鼎', '吳志清', '邊緣平台', '生態系', 'edge'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:05', href: 'index.html#agenda',
    title: '用 Edge Impulse 簡化 Edge AI 開發與部署流程 — 林宣百', titleEn: 'Simplify Edge AI with Edge Impulse — 林宣百',
    body: '11:05–11:30 Edge Impulse Inc.，林宣百 技術應用工程師, 高通技術公司',
    bodyEn: '11:05–11:30 Edge Impulse Inc., 林宣百, FAE, Qualcomm.',
    tags: ['edge impulse', '林宣百', 'edge ai', '部署', 'deploy'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:30', href: 'index.html#agenda',
    title: '高效率 AI On-Prem 解決方案實現 Edge LLM 規模化部署 — 施良岳', titleEn: 'Scalable Edge LLM with AI On-Prem — 施良岳',
    body: '11:30–11:55 安提國際 Aetina，施良岳 MegaEdge 邊緣運算平台 產品部副理',
    bodyEn: '11:30–11:55 Aetina, 施良岳, MegaEdge Product Manager.',
    tags: ['aetina', '安提', '施良岳', 'on-prem', 'edge llm', 'megaedge', 'llm'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:55', href: 'index.html#agenda',
    title: 'Trusted Agentic AI Beyond the Cloud — 鍾哲民', titleEn: 'Trusted Agentic AI Beyond the Cloud — 鍾哲民',
    body: '11:55–12:20 行動貝果 MoBagel，鍾哲民 美商行動貝果 執行長暨共同創辦人',
    bodyEn: '11:55–12:20 MoBagel, 鍾哲民, CEO & Co-founder.',
    tags: ['mobagel', '行動貝果', '鍾哲民', 'agentic ai', 'cloud'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 13:30', href: 'index.html#agenda',
    title: 'IQ9 實作演練 I — 黃誌祥', titleEn: 'IQ9 Hands-on I — 黃誌祥',
    body: '13:30–14:30 1. IQ Studio 平台概覽 2. 韌體燒錄 & 環境初始化｜黃誌祥 智能周邊應用事業處軟體研發部副理',
    bodyEn: '13:30–14:30 1. IQ Studio overview 2. Firmware flashing & environment init. 黃誌祥.',
    tags: ['iq9', 'iq studio', '黃誌祥', '韌體', '燒錄', '實作演練', 'hands-on'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 14:50', href: 'index.html#agenda',
    title: 'IQ9 實作演練 II — 黃誌祥', titleEn: 'IQ9 Hands-on II — 黃誌祥',
    body: '14:50–15:50 1. 高通模型下載與優化轉換 2. 模型轉換與部屬 AI PoC 展示與驗證｜黃誌祥',
    bodyEn: '14:50–15:50 1. Qualcomm model download & optimization 2. Model conversion & AI PoC demo. 黃誌祥.',
    tags: ['iq9', '模型', '優化', 'poc', '黃誌祥', '實作演練', 'hands-on', 'model'] },

  // ----- Handouts -----
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: '攜帶清單', titleEn: 'What to bring',
    body: 'Windows 筆電、EXMP-Q911、type-c to USB、DP2HDMI、HDMI2HDMI、螢幕、UVC camera、USB2UART',
    bodyEn: 'Windows laptop, EXMP-Q911, type-c to USB, DP2HDMI, HDMI2HDMI, monitor, UVC camera, USB2UART.',
    tags: ['checklist', '攜帶', 'q911', 'camera', 'uart', 'hdmi'] },
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: '現場 WiFi 與 Qualcomm 帳號', titleEn: 'On-site WiFi & Qualcomm account',
    body: 'WiFi 名稱與密碼現場公布；事前請建立 Qualcomm 帳號 qualcomm.com',
    bodyEn: 'WiFi name/password announced on-site; create a Qualcomm account at qualcomm.com beforehand.',
    tags: ['wifi', 'qualcomm', 'account', '帳號', '網路'] },
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: 'iQ-Studio / iQ-Foundry repo', titleEn: 'iQ-Studio / iQ-Foundry repos',
    body: 'GitHub 教材：github.com/InnoIPA/iQ-Studio、github.com/InnoIPA/iQ-Foundry',
    bodyEn: 'GitHub material: github.com/InnoIPA/iQ-Studio and github.com/InnoIPA/iQ-Foundry.',
    tags: ['github', 'iq-studio', 'iq-foundry', 'repo', 'innoipa'] },
];
